(defun is-palindrome (num)
  (equal (write-to-string num) (reverse (write-to-string num))))
(defun max-pal ()
  (setf winner 0)
  (do ((prod1 999 (1- prod1)))
    ((< prod1 100) winner)
    (do ((prod2 999 (1- prod2)))
      ((< prod2 100) nil)
      (setf product (* prod1 prod2))
      (if (is-palindrome product) (setf winner (max winner product))))))
(print (max-pal))
;(print (is-palindrome 4719))
;(print (is-palindrome 99112221199))

